apiVersion: v1
appVersion: "0.1"
description: A Helm chart for Volcano
home: https://volcano.sh
icon: https://raw.githubusercontent.com/volcano-sh/charts/master/docs/images/volcano-logo.png
maintainers:
- email: wang.platform@gmail.com
  name: william-wang
- email: kevinwzf0126@gmail.com
  name: kevin-wangzefeng
name: volcano
sources:
- https://github.com/volcano-sh/volcano
version: 1.8.2
